### ISSUE TITLE
请问 如何打开admin下的页面，默认是index下的目录

### ISSUE THREAD

**Issue by huyongyong1992** [Faithree/multiple-vue-amazing#2]
因为浏览器包括web服务器默认打开的就是index.html 你可以改服务器的默认打开的文件配置，或者后台重定向。反向代理等配置，

**Comment by Faithree** [comment]
因为浏览器包括web服务器默认打开的就是index.html 你可以改服务器的默认打开的文件配置，或者后台重定向。反向代理等配置，
